name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: godwin1605/aifa-backend
  GKE_CLUSTER: alfavox-cluster
  GKE_ZONE: us-central1-a

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:$GITHUB_SHA .
        docker build -t $IMAGE_NAME:latest .
        
    - name: Push Docker image
      run: |
        docker push $IMAGE_NAME:$GITHUB_SHA
        docker push $IMAGE_NAME:latest

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup GCP Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Setup Gcloud
      uses: google-github-actions/setup-gcloud@v1
        
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        
    - name: Deploy to GKE
      run: |
        kubectl set image deployment/aifa-backend aifa-backend=$IMAGE_NAME:$GITHUB_SHA
        kubectl rollout status deployment/aifa-backend
        
    - name: Verify deployment
      run: |
        kubectl get deployments
        kubectl get pods
        kubectl get services